create table if not exists tales (id int auto_increment, player_name VARCHAR(100), age INT, tale VARCHAR(100), primary key (id));

insert into tales (player_name, age, tale) values ('Idősebbik mostohatestvér', 22, 'CINDERELLA');
insert into tales (player_name, age, tale) values ('Gonosz Királyné', 34, 'SNOWWHITE');
insert into tales (player_name, age, tale) values ('Morgó', 198, 'SNOWWHITE');
insert into tales (player_name, age, tale) values ('Gazdag ember', 42, 'CINDERELLA');
insert into tales (player_name, age, tale) values ('Szende', 256, 'SNOWWHITE');
insert into tales (player_name, age, tale) values ('Nagy királykisasszony', 28, 'FROGPRINCE');
insert into tales (player_name, age, tale) values ('Vadász', 56, 'SNOWWHITE');
insert into tales (player_name, age, tale) values ('Hófehérke', 23, 'SNOWWHITE');
insert into tales (player_name, age, tale) values ('Királyfi', 26, 'SNOWWHITE');
insert into tales (player_name, age, tale) values ('Tudor', 392, 'SNOWWHITE');
insert into tales (player_name, age, tale) values ('Királyné', 44, 'SLEEPINGBEAUTY');
insert into tales (player_name, age, tale) values ('Hapci', 741, 'SNOWWHITE');
insert into tales (player_name, age, tale) values ('Bűbájos vénasszony', 69, 'SLEEPINGBEAUTY');
insert into tales (player_name, age, tale) values ('Királyfi', 22, 'SLEEPINGBEAUTY');
insert into tales (player_name, age, tale) values ('Piroska', 9, 'LITTLEREDRIDINGHOOD');
insert into tales (player_name, age, tale) values ('Királyfi', 23, 'CINDERELLA');
insert into tales (player_name, age, tale) values ('Farkas', 11, 'LITTLEREDRIDINGHOOD');
insert into tales (player_name, age, tale) values ('Békakirályfi', 27, 'FROGPRINCE');
insert into tales (player_name, age, tale) values ('Királyné', 25, 'SNOWWHITE');
insert into tales (player_name, age, tale) values ('Hamupipőke', 19, 'CINDERELLA');
insert into tales (player_name, age, tale) values ('Királyné', 52, 'FROGPRINCE');
insert into tales (player_name, age, tale) values ('Kuka', 538, 'SNOWWHITE');
insert into tales (player_name, age, tale) values ('Király', 56, 'FROGPRINCE');
insert into tales (player_name, age, tale) values ('Szundi', 387, 'SNOWWHITE');
insert into tales (player_name, age, tale) values ('Vadász', 63, 'LITTLEREDRIDINGHOOD');
insert into tales (player_name, age, tale) values ('Galamb', 3, 'CINDERELLA');
insert into tales (player_name, age, tale) values ('Király', 45, 'SNOWWHITE');
insert into tales (player_name, age, tale) values ('Vidor', 276, 'SNOWWHITE');
insert into tales (player_name, age, tale) values ('Fiatalabbik mostohatestvér', 22, 'CINDERELLA');
insert into tales (player_name, age, tale) values ('Idősebbik mostohatestvér', 22, 'CINDERELLA');
insert into tales (player_name, age, tale) values ('Gonosz mostoha', 40, 'CINDERELLA');
insert into tales (player_name, age, tale) values ('Kicsi királykisasszony', 21, 'FROGPRINCE');
insert into tales (player_name, age, tale) values ('Nagymama', 71, 'LITTLEREDRIDINGHOOD');
insert into tales (player_name, age, tale) values ('Király', 49, 'SLEEPINGBEAUTY');
insert into tales (player_name, age, tale) values ('Közepes királykisasszony', 25, 'FROGPRINCE');
insert into tales (player_name, age, tale) values ('Tükör', 1487, 'SNOWWHITE');
insert into tales (player_name, age, tale) values ('Csipkerózsika', 18, 'SLEEPINGBEAUTY');
insert into tales (player_name, age, tale) values ('János, a kocsis', 62, 'FROGPRINCE');
insert into tales (player_name, age, tale) values ('Gazdag ember felesége', 37, 'CINDERELLA');