create table if not exists ladybirds (id int auto_increment, hungarian_name varchar(100), latin_name varchar(100), genus VARCHAR(100), number_of_points INT, primary key (id));

insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('nádi félböde', '(Coccidula rufa)', 'félbödeformák (Coccidulinae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('mocsári félböde', '(Coccidula scutellata)', 'félbödeformák (Coccidulinae)', 3);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('szalagos félböde', '(Rhyzobius chrysomeloides)', 'félbödeformák (Coccidulinae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('félholdas félböde', '(Rhyzobius litura)', 'félbödeformák (Coccidulinae) ', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('pusztai földiböde', '(Tetrabrachys connatus)', 'félbödeformák (Coccidulinae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('mezei szerecsenböde', '(Hyperaspis campestris)', 'bödiceformák (Scymninae)', 2);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('egyszínű szerecsenböde', '(Hyperaspis concolor)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('homoki szerecsenböde', '(Hyperaspis erythrocephala)', 'bödiceformák (Scymninae)', 6);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('vállcseppes szerecsenböde', '(Hyperaspis pseudopustulata)', 'bödiceformák (Scymninae)', 1);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('négycseppes szerecsenböde', '(Hyperaspis quadrimaculata)', 'bödiceformák (Scymninae)', 4);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('tojásdad szerecsenböde', '(Hyperaspis reppensis)', 'bödiceformák (Scymninae)', 2);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('liszteske-bödice', '(Clitostethus arcuatus)', 'bödiceformák (Scymninae)', 1);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('kétpettyes törpebödice', '(Nephus bipunctatus)', 'bödiceformák (Scymninae)', 2);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('kétjegyes törpebödice', '(Nephus bisignatus claudiae)', 'bödiceformák (Scymninae)', 2);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('feketés törpebödice', '(Nephus nigricans)', 'bödiceformák (Scymninae)', 2);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('négyfoltos törpebödice', '(Nephus quadrimaculatus)', 'bödiceformák (Scymninae)', 4);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('korongfoltos törpebödice', '(Nephus redtenbacheri)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('Ulbrich-törpebödice', '(Nephus ulbrichi)', 'bödiceformák (Scymninae)', 4);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('halványfoltos törpebödice', '(Scymniscus anomus)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('Horion-törpebödice', '(Scymniscus horioni)', 'bödiceformák (Scymninae)', 2);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('korzikai törpebödice', '(Scymniscus semirufus)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('ostoros bödice', '(Scymnus flagellisiphonatus)', 'bödiceformák (Scymninae)', 2);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('sziki bödice', '(Scymnus sacium)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('fekete bödice', '(Scymnus ater)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('sárgavégű bödice', '(Scymnus haemorrhoidalis)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('gesztenyebarna bödice', '(Scymnus limbatus)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('barna fenyvesbödice', '(Scymnus abietis)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('sárgafejű bödice', '(Scymnus auritus)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('csúcsfoltos bödice', '(Scymnus ferrugatus)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('gömbölyded bödice', '(Scymnus fraxini)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('kis fenyvesbödice', '(Scymnus impexus)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('sárgás bödice', '(Scymnus silesiacus)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('négyfoltos bödice', '(Scymnus subvillosus)', 'bödiceformák (Scymninae)', 4);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('varratsávos bödice', '(Scymnus suturalis)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('kis kerekbödice', '(Scymnus apetzi)', 'bödiceformák (Scymninae)', 2);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('széleslábú bödice', '(Scymnus doriae)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('feketecombú bödice', '(Scymnus femoralis)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('közönséges bödice', '(Scymnus frontalis)', 'bödiceformák (Scymninae)', 2);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('vállfoltos bödice', '(Scymnus interruptus)', 'bödiceformák (Scymninae)', 2);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('négycseppes bödice', '(Scymnus magnomaculatus)', 'bödiceformák (Scymninae)', 4);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('nagyfoltos bödice', '(Scymnus marginalis)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('fekete fenyvesbödice', '(Scymnus nigrinus)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('vörösfoltos bödice', '(Scymnus rubromaculatus)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('pontsoros bödice', '(Scymnus schmidti)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('nagy kerekbödice', '(Scymnus suffrianioides apetzoides)', 'bödiceformák (Scymninae)', 4);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('atkász bödice', '(Stethorus pusillus)', 'bödiceformák (Scymninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('szalagos szerecsenkata', '(Chilocorus bipustulatus)', 'szerecsenkata-formák (Chilocorinae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('vesefoltos szerecsenkata', '(Chilocorus renipustulatus)', 'szerecsenkata-formák (Chilocorinae)', 2);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('négyfoltos szerecsenkata', '(Exochomus quadripustulatus)', 'szerecsenkata-formák (Chilocorinae)', 4);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('egyszínű szerecsenkata', '(Parexochomus nigromaculatus)', 'szerecsenkata-formák (Chilocorinae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('négypettyes szerecsenkata', '(Platynaspis luteorubra)', 'szerecsenkata-formák (Chilocorinae)', 4);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('kétpettyes katicabogár', '(Adalia bipunctata)', 'katicaformák (Coccinellinae)', 2);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('rajzos katica', '(Adalia conglomerata)', 'katicaformák (Coccinellinae)', 11);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('tízpettyes katica', '(Adalia decempunctata)', 'katicaformák (Coccinellinae)', 10);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('szemfoltos katica', '(Anatis ocellata)', 'katicaformák (Coccinellinae)', 15);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('tizenkilencpettyes katica', '(Anisosticta novemdecimpunctata)', 'katicaformák (Coccinellinae)', 19);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('sárga katica', '(Aphidecta obliterata)', 'katicaformák (Coccinellinae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('tízcseppes füsskata', '(Calvia decemguttata)', 'katicaformák (Coccinellinae)', 10);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('tizennégycseppes füsskata', '(Calvia quatuordecimguttata)', 'katicaformák (Coccinellinae)', 14);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('tizenötcseppes füsskata', '(Calvia quindecimguttata)', 'katicaformák (Coccinellinae)', 15);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('alhavasi katica', '(Ceratomegilla notata)', 'katicaformák (Coccinellinae)', 11);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('bogáncskatica', '(Ceratomegilla undecimnotata)', 'katicaformák (Coccinellinae)', 9);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('csarabkatica', '(Coccinella hieroglyphica)', 'katicaformák (Coccinellinae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('hangyászkatica', '(Coccinella magnifica)', 'katicaformák (Coccinellinae)', 9);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('ötpettyes katica', '(Coccinella quinquepunctata)', 'katicaformák (Coccinellinae)', 5);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('hárompettyes katica', '(Coccinella saucerottii)', 'katicaformák (Coccinellinae)', 3);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('hétpettyes katicabogár', '(Coccinella septempunctata)', 'katicaformák (Coccinellinae)', 7);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('sziki tizenegypettyes katica', '(Coccinella undecimpunctata tripunctata)', 'katicaformák (Coccinellinae)', 11);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('közönséges tizenegypettyes katica', '(Coccinella undecimpunctata undecimpunctata)', 'katicaformák (Coccinellinae)', 11);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('feketesárga katóka', '(Coccinula quatuordecimpustulata)', 'katicaformák (Coccinellinae)', 14);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('oldalsávos katóka', '(Coccinula sinuatomarginata)', 'katicaformák (Coccinellinae)', 8);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('tizenhatcseppes füsskata', '(Halyzia sedecimguttata)', 'katicaformák (Coccinellinae)', 16);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('harlekinkatica', '(Harmonia axyridis)', 'katicaformák (Coccinellinae)', 18);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('négypettyes katica', '(Harmonia quadripunctata)', 'katicaformák (Coccinellinae)', 16);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('hétfoltos katica', '(Hippodamia septemmaculata)', 'katicaformák (Coccinellinae)', 7);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('mocsári katica', '(Hippodamia tredecimpunctata)', 'katicaformák (Coccinellinae)', 13);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('tizenhárompettyes katica', '(Hippodamia variegata)', 'katicaformák (Coccinellinae)', 13);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('tizennyolccseppes füsskata', '(Myrrha octodecimguttata)', 'katicaformák (Coccinellinae)', 18);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('sávos füsskata', '(Myzia oblongoguttata)', 'katicaformák (Coccinellinae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('rózsás katica', '(Oenopia conglobata)', 'katicaformák (Coccinellinae)', 16);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('fekete katica', '(Oenopia impustulata)', 'katicaformák (Coccinellinae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('bokorerdei katica', '(Oenopia lyncea agnatha)', 'katicaformák (Coccinellinae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('tizennégypettyes füsskata', '(Propylea quatuordecimpunctata)', 'katicaformák (Coccinellinae)', 14);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('huszonkétpettyes katica', '(Psyllobora vigintiduopunctata)', 'katicaformák (Coccinellinae)', 22);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('húszcseppes füsskata', '(Sospita vigintiguttata)', 'katicaformák (Coccinellinae)', 20);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('tizenhatpettyes katica', '(Tytthaspis sedecimpunctata)', 'katicaformák (Coccinellinae)', 16);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('tizenkétcseppes füsskata', '(Vibidia duodecimguttata)', 'katicaformák (Coccinellinae)', 12);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('pázsitfűböde', '(Cynegetis impunctata)', 'bödeformák (Epilachninae)', 0);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('földitökböde', '(Henosepilachna argus)', 'bödeformák (Epilachninae)', 11);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('magrugóböde', '(Henosepilachna elaterii)', 'bödeformák (Epilachninae)', 24);
insert into ladybirds (hungarian_name, latin_name, genus, number_of_points) values ('lucernaböde', '(Subcoccinella vigintiquatuorpunctata)', 'bödeformák (Epilachninae)', 22);
